export default ({
    "equal_1": "",
    "equal_2": "",
    "equal_3": "",
    "equal_4": "",
    "equal_5": "",
    "equal_6": "",
    "bonus": "",
    "tris": "",
    "poker": "",
    "full": "",
    "little_straight": "",
    "big_straight": "",
    "yahtzee": "",
    "chance": "",
    "yahtzee_bonus": "",
})